name: build

on:
  push:
env:
  PAWPAW_SKIP_LV2: 0

jobs:
  linux:
    strategy:
      matrix:
        target: [linux-x86_64]
    runs-on: ubuntu-22.04
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: ${{ matrix.target }}
          extraargs: SSE_CFLAGS="" FFT_FLAG="" lv2
          lto: false
          pawpaw: true

  arm64:
    strategy:
      matrix:
        target: [linux-arm64]
    runs-on: ubuntu-22.04
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          extraargs: lv2
          pawpaw: true

  linux-optimised:
    strategy:
      matrix:
        target: [linux-x86_64]
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          postfix: -v3
          extraargs: lv2
          lto: false
          pawpaw: true

  linux-standalone:
    strategy:
      matrix:
        target: [linux-x86_64]
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          postfix: -app
          extraargs: standalone
          lto: false
          pawpaw: true

  windows-optimised:
    strategy:
      matrix:
        target: [win64]
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          postfix: -v3
          extraargs: lv2
          pawpaw: true

  windows:
    strategy:
      matrix:
        target: [win64]
    runs-on: ubuntu-22.04
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          extraargs: SSE_CFLAGS="" FFT_FLAG="" lv2
          pawpaw: true

  windows-standalone:
    strategy:
      matrix:
        target: [win64]
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          postfix: -app
          extraargs: standalone
          pawpaw: true

  source:
    runs-on: ubuntu-22.04
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: source

